### ISSUE TITLE
Date format YYYY-MM-DD

### ISSUE THREAD

**Issue by mariansauter** [ja-ka/violentmonkey#2]
Great script!

Would it be possible to have the date in the filename not be DD_MM_YYYY but YYYY-MM-DD. The latter is much easier for archiving purposes.

**Comment by joseantonomh** [comment]
Adding the following .map statement does the trick. I hope it helps :)  
           
...

                    .get()
                    .map(text => {
                      var dateMatch = Array.from(text.matchAll(/^([0-9]{2})_([0-9]{2})_([0-9]{4})$/gm));
                      if(dateMatch.length == 1){
                        return dateMatch[0][3] + "-" +  dateMatch[0][2] + "-" + dateMatch[0][1];
                      } else{
                        return text;
                      }
                    })
                    .join('_') + ".pdf";

....

**Comment by ja-ka** [comment]
Hi @mariansauter, your request has been implemented with the latest version! :) You'll find a new button _Dateinamen ändern_ next to _Alle herunterladen_. Enjoy!
