### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by giannis371** [ja-ka/violentmonkey#6]
I just run the script for the first time and
I get an error pop up
banking.ing.de
Es ist ein Fehler aufgetreten.

Can i find somewhere any logs?

**Comment by ja-ka** [comment]
I received word from another person that it stopped working a few days ago. Seems like ING changed their side of the code. I’m traveling right now with no access to my laptop, but I’ll check it again once I’m back home. I’ll post another update here then.

**Comment by giannis371** [comment]
Thanks!
