### ISSUE TITLE
Proper Escape of german umlauts (ä,ö,ü,..)

### ISSUE THREAD

**Issue by tinooo** [ja-ka/violentmonkey#8]
First of all, thanks for your Script. 

There is a fork of your Repo and he did include proper escaping of the file names. I think that would make a great addition. 
https://github.com/Eckaaaaaat/violentmonkey/commit/ee7d8dddcb09cdd302d2417f0f135fca97bc0255

Should I prepare a pull request for you, would you consider merging it?

**Comment by ja-ka** [comment]
@tinooo thanks for the hint! Yes, please do, I'll merge it then.
